const letras = ["A","B","C","D"]
console.log("abaixo o vetor original")
console.log(letras)
console.log("")
console.log("abaixo o slice -2")
const letras2 = letras.slice(-2)
console.log(letras2)
console.log("")
console.log("abaixo o slice 0,-1")
const letras3 = letras.slice(0,-1)
console.log(letras3)
console.log("")
const retira = letras.splice(2,1)
console.log("Compare agora os dois vetores, o original e o que sobrou depois do splice")
console.log(letras)
console.log(retira)
