const cidades = ['pelotas']
console.log(cidades)
console.log('push São Lourenço....')
cidades.push('São Lourenço')
console.log(cidades)
console.log("")
console.log("agora unshift PoA....")
cidades.unshift("Porto Alegre")
console.log(cidades)
console.log("")
console.log("pop .......")
cidades.pop()
console.log(cidades)
console.log("")
console.log("Agora shift")
cidades.shift()
console.log(cidades)
